server:
  port: ${SYS_PORT}
db:
  name: bms_warehouse_keeper
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_DB_HOSTNAME}:${MYSQL_DB_PORT}/${db.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
    type: com.alibaba.druid.pool.DruidDataSource
  sql:
    init:
      username: ${MYSQL_DB_USERNAME}
      password: ${MYSQL_DB_PASSWORD}
      mode: always
      schema-locations: classpath*:schema/schema.sql
      data-locations: classpath*:data/data.sql


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

swagger:
  enabled: true
  base-package: 'io.bms.bmswk'
  title: 'Black Mesa Warehouse Keeper API system'
  description: 'API Documentation for the warehouse inventory management system'
  version: '1.0'
  contact:
    name: '996worker'
    url: 'https://www.996workers.icu'
  authorization:
    key-name: 'Authorization'
    name: 'Bearer JWT Token (e.g. Bearer *****)'

logging:
  level:
    io:
      bms:
        bmswk: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
